


DROP TABLE articles;

CREATE TABLE articles(
  article_id serial PRIMARY KEY,
  title VARCHAR(500),
  description VARCHAR(500),
  author VARCHAR (500),
  url VARCHAR(500),
  image VARCHAR(500),
  published DATE,
  source VARCHAR(50),
  x_score INTEGER
);

INSERT INTO articles VALUES ( 193, 'The Title 1, a longer title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 25 );
INSERT INTO articles VALUES ( 123, 'The Title 1, a longer title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 25 );
INSERT INTO articles VALUES ( 111, 'The Title 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 75 );
INSERT INTO articles VALUES ( 222, 'The Title 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 221, 'The Title 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 223, 'The Title 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://placehold.it/200x300', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 333, 'The Title 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://placehold.it/200x300', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 788, 'The Title 1, a longer title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 25 );
INSERT INTO articles VALUES ( 331, 'The Title 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://placehold.it/200x300', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 444, 'The Title 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://placehold.it/200x300', '2017-02-08 02:40:12', 'the-huffington-post', 25 );
INSERT INTO articles VALUES ( 441, 'The Title 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://placehold.it/200x300', '2017-02-08 02:40:12', 'the-huffington-post', 75 );
INSERT INTO articles VALUES ( 878, 'The Title 1, a longer title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 25 );
INSERT INTO articles VALUES ( 888, 'The Title 1, a longer title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 25 );
INSERT INTO articles VALUES ( 334, 'The Title 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 442, 'The Title 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 445, 'The Title 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 455, 'The Title 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
INSERT INTO articles VALUES ( 552, 'The Title 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'The Author', 'https://google.com', 'http://fillmurray.com/150/100', '2017-02-08 02:40:12', 'the-huffington-post', 50 );
